version: "3"

services:
  frontend:
      image: habibo1234/investment-fe:2.0
      container_name: frontend
      ports:
          - 3000:3000
      restart: always
      depends_on:
        - backend
      volumes:
        - build_folder:/react/build

  backend:
    image: habibo1234/investment-be:6.0
    container_name: backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend

volumes:
   build_folder: